AP-28 Jacked bootstrap form for billing, made columns and row
istuart50/ApolloOneStorefront pull request #8
Opened 2023-05-26 22:12 UTC by lonatTee-yah

git push --set-upstream origin AP-28_billing-form

2023-05-26 22:57 UTC, istuart50 approved these changes
Looks good!

2023-05-26 23:46 UTC, GrantGriffin requested changes

2023-05-26 23:46 UTC, GrantGriffin commented on checkout.html
> +            <div class="col1">
this says col1 which is broken would be `col-1` but that would be only a column wide.  Maybe you meant to do `col-6` or just `col`?

2023-05-26 23:46 UTC, GrantGriffin commented on checkout.html
> +            <div class="col2">
this should also be probably `col-6`

2023-05-27 19:46 UTC, GrantGriffin approved these changes

2023-05-27 19:50 UTC, merged